solution for array exercise
Leenday/study pull request #1
Opened 2020-09-13 14:38 UTC by Leenday

2020-10-14 18:37 UTC, artempartos requested changes

2020-10-14 18:37 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +          for num in arr
в руби никогда не пишут for )
есть each/map/reduce - все пользуются ими

2020-10-14 18:37 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        for num in array
тоже самое

2020-10-14 18:37 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +          slice_first_half = ->(collection) { collection[0, collection.length / 2] }
ну очень сложно написано

2020-10-18 06:18 UTC, Leenday commented on test/exercise/arrays/solution.rb
> +          for num in arr
Переписал на reduce, спасибо

2020-10-18 06:19 UTC, Leenday commented on test/exercise/arrays/solution.rb
> +          slice_first_half = ->(collection) { collection[0, collection.length / 2] }
Постарался упростить

2020-10-19 11:38 UTC, Andrew8xx8 requested changes

2020-10-19 11:38 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        find_max_num = lambda do |arr|
Это лучше вынести в отдельный метод

2020-10-21 19:09 UTC, Leenday commented on test/exercise/arrays/solution.rb
> +        find_max_num = lambda do |arr|
Спасибо, вынес в отдельный метод

2020-10-29 18:01 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +        highest_num = find_max_num(array)
при именование практически не используется сравнительная степень

2020-10-29 18:07 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +          slice_first_half = ->(collection) { collection[0, collection.length / 2] }
проще не стало) попробуй сделать с помощь рекурсии без лямбд и калл

2020-10-30 07:17 UTC, Leenday commented on test/exercise/arrays/solution.rb
> +          slice_first_half = ->(collection) { collection[0, collection.length / 2] }
Благодарю, вынес в отдельный метод без лямбд. Еще поработать над методом iter?

2020-10-30 07:17 UTC, Leenday commented on test/exercise/arrays/solution.rb
> +        highest_num = find_max_num(array)
Изменил на `max_nam`, благодарю

2020-11-02 19:26 UTC, greybutton approved these changes

2020-11-11 18:03 UTC, merged