fp exercise solution
Leenday/study pull request #2
Opened 2020-09-16 18:33 UTC by Leenday

2020-10-14 18:39 UTC, artempartos requested changes

2020-10-14 18:39 UTC, artempartos commented on test/exercise/fp/solution.rb
> +        result = array.map do |film|
пользуйся примитивами функционального программирования select/map/reduce

2020-10-14 18:39 UTC, artempartos commented on test/exercise/fp/solution.rb
> +        result = array.map do |film|
O(n) особо учитывать не будем )

2020-10-14 18:39 UTC, artempartos commented on test/exercise/fp/solution.rb
> +        films.map { |film| film['rating_kinopoisk'].to_f >= threshold ? film['name'] : '' }.reduce(0) { |sum, name| sum + name.count('и') }
давай попробуем https://blog.saeloun.com/2019/05/25/ruby-2-7-enumerable-filter-map.html тут

2020-10-18 10:39 UTC, Leenday commented on test/exercise/fp/solution.rb
> +        films.map { |film| film['rating_kinopoisk'].to_f >= threshold ? film['name'] : '' }.reduce(0) { |sum, name| sum + name.count('и') }
Благодарю, использовал. Не знал о существовании такого метода

2020-10-18 10:40 UTC, Leenday commented on test/exercise/fp/solution.rb
> +        result = array.map do |film|
Переписал с `reduce`, однако рубокоп ругнулся "Style/EachWithObject: Use `each_with_object` instead of `reduce`"

2020-10-19 11:39 UTC, Andrew8xx8 requested changes

2020-10-19 11:39 UTC, Andrew8xx8 commented on test/exercise/fp/solution.rb
> +        array.each_with_object(accumulator) do |film, acc|
Это выглядит как императивный, а не декларативный потход. Надо использовать map и reduce, в которых определено, что сделать, а не как сделать.

2020-10-19 20:19 UTC, Leenday commented on test/exercise/fp/solution.rb
> +        array.each_with_object(accumulator) do |film, acc|
Благодарю, пересмотрел написание метода.

2020-10-21 10:24 UTC, Andrew8xx8 approved these changes

2020-11-11 18:04 UTC, merged