solution of functional primitives 2
Leenday/study pull request #3
Opened 2020-09-23 19:08 UTC by Leenday

2020-10-14 18:40 UTC, artempartos requested changes

2020-10-14 18:40 UTC, artempartos commented on test/exercise/fp2/solution.rb
> +        acc = Exercise::Fp2::MyArray.new
создание массива и напихивание в него в цикле - верный признак того что надо использовать reduce. Заиспользуй тут и в my_compact свой же написанный my_reduce

2020-10-18 15:17 UTC, Leenday commented on test/exercise/fp2/solution.rb
> +        acc = Exercise::Fp2::MyArray.new
Использовал, спасибо)

2020-10-19 11:40 UTC, Andrew8xx8 approved these changes

2020-11-11 18:04 UTC, merged